baseURL = "https://ajdurant.co.uk/"
languageCode = "en-gb"
title = "ajdurant - Andy Durant"

copyright = "Copyright &copy; 2019 - AJ Durant"
canonifyurls = true
theme = "kiera"

paginate = 10

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Andrew Durant"
    github = "AJDurant"
    gitlab = ""
    linkedin = "andydurant"
    facebook = ""
    twitter = "andydurant"
    instagram = ""

[params]
    tagline = "Random notes and things"

[[menu.main]]
    name = "Home" #Name in the navigation bar
    weight = 10 #The larger the weight, the more on the right this item will be
    url = "/" #URL address
[[menu.main]]
    name = "Posts"
    weight = 20
    url = "/posts/"
