# Basic config
baseURL = "https://ajdurant.co.uk/"
theme = "hugo-simple"
languageCode = "en-gb"
title = "Andy Durant"
copyright = "© AJ Durant"

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

canonifyurls = true

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true
googleAnalytics = ""

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
title = "Andy Durant"
description = "Random notes and things"
dateFormat = "2006-01-02"
hideMadeWithLine = true
hideRSSLink = false

[params.author]
name = "Andrew Durant"
github = "AJDurant"
gitlab = "AJDurant"
linkedin = "andydurant"

[[menus.main]]
name = "Hello!" #Name in the navigation bar
pageRef = "/"
weight = 10
[[menus.main]]
name = "Blog"
pageRef = "/blog"
weight = 20

[pagination]
pagerSize = 16